version: "3.9"

services:
  backend:
    build: ./flight-search-backend
    container_name: flight-backend
    ports:
      - "3000:3000"
    volumes:
      - ./flight-search-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build: ./flight-search-frontend
    container_name: flight-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./flight-search-frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
